export const CLIENT_INFO_REQUEST = "CLIENT_INFO_REQUEST";
export const CLIENT_INFO_SUCCEEDED = "CLIENT_INFO_SUCCEEDED";
export const CLIENT_INFO_FAILED = "CLIENT_INFO_FAILED";

export const CLIENT_INFO_SEND_REQUEST = "CLIENT_INFO_SEND_REQUEST";
export const CLIENT_INFO_SEND_SUCCEEDED = "CLIENT_INFO_SEND_SUCCEEDED";
export const CLIENT_INFO_SEND_FAILED = "CLIENT_INFO_SEND_FAILED";
