export const PORTFOLIO_DATA_REQUESTED = "PORTFOLIO_DATA_REQUESTED";
export const PORTFOLIO_DATA_SUCCEEDED = "PORTFOLIO_DATA_SUCCEEDED";
export const PORTFOLIO_DATA_FAILED = "PORTFOLIO_DATA_FAILED";
export const PORTFOLIO_DATA_ERROR = "PORTFOLIO_DATA_ERROR";
